on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    permissions:
      pages: write
      id-token: write
    strategy:
      matrix:
        targets:
          - http://testphp.vulnweb.com
          - https://www.hahwul.com
          - https://owasp.org
          - https://www.zaproxy.org    
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: ${{matrix.targets}}
          rules_file_name: '.zap/gen.conf'
          cmd_options: '--user root'
      - name: Checking...
          run: chmod -R 755 /zap/wrk/; ls -la; 





# jobs:
#   zap_scan:
#     permissions:
#       pages: write
#       id-token: write
#     strategy:
#       matrix:
#         target:
#           - http://testphp.vulnweb.com
#           - https://www.hahwul.com
#           - https://owasp.org
#           - https://www.zaproxy.org
#     runs-on: ubuntu-latest
#     name: Scan the web application
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           ref: main
#       - name: mkdir 777 to resolve error
#         run: mkdir –m -p 777 /zap/wrk/
#       - name: ZAP Scan
#         uses: zaproxy/action-baseline@v0.10.0
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           docker_name: ghcr.io/zaproxy/zaproxy:stable
#           target: ${{ matrix.target }}
#           issue_title: ZAP Baseline Scan
#           fail_action: false
#           # rules_file_name: '.zap/gen.conf'
#           cmd_options: "-a"
