on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    permissions:
      pages: write
      id-token: write     
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: MZAP Env
        uses: hahwul/mzap@v1.2.0
        with:
          arguments: '--urls urls.txt'
