on: 
  push:
    branches:
      - main
  # workflow_call:
  #   inputs:
  #     target:
  #       description: 'the base url to target'
  #       default: 'http://localhost:3000'
  #       required: false
  #       type: string

jobs:
  zap_scan:
    permissions:
      pages: write
      id-token: write
    strategy:
      matrix:
        target:
          - http://testphp.vulnweb.com
          - https://www.hahwul.com
          - https://owasp.org
          - https://www.zaproxy.org    
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      # - name: Print the input target to STDOUT
      #   run: echo Next step will scan:  ${{ matrix.target }}          
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: ${{ matrix.target }}
          # rules_file_name: '.z  ap/gen.conf'
          cmd_options: '-a'

  # zap_scan:
  #   runs-on: ubuntu-latest
  #   name: Scan the webapplication
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         ref: master
  #     - name: ZAP Scan
  #       uses: zaproxy/action-baseline@v0.12.0
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
  #         target: 'https://www.zaproxy.org'
  #         rules_file_name: '.zap/rules.tsv'
  #         cmd_options: '-a'


# jobs:
#   example_matrix:
#     strategy:
#       matrix:
#         os: [ubuntu-22.04, ubuntu-20.04]
#         version: [10, 12, 14]
#     runs-on: ${{ matrix.os }}
#     steps:
#       - uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.version }}        