on: 
  push:
    branches:
      - main
  workflow_call:
    inputs:
      target:
        description: 'the base url to target'
        default: 'http://localhost:3000'
        required: false
        type: string

jobs:
  zap_scan:
    permissions:
      pages: write
      id-token: write     
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Print the input target to STDOUT
        run: echo The username is ${{ inputs.target }}
