on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    permissions:
      pages: write
      id-token: write
    strategy:
      matrix:
        target:
          - http://testphp.vulnweb.com
          - https://www.hahwul.com
          - https://owasp.org
          - https://www.zaproxy.org
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          target: ${{ matrix.target }}
          issue_title: "ZAP Baseline Scan"
          fail_action: false
          # rules_file_name: '.z  ap/gen.conf'
          cmd_options: "-a"
